using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
// [assembly: AssemblyTitle("Vizor")]
// [assembly: AssemblyDescription("")]
// [assembly: AssemblyConfiguration("")]
// [assembly: AssemblyCompany("")]
// [assembly: AssemblyProduct("Vizor")]
// [assembly: AssemblyCopyright("Copyright ©  2024")]
// [assembly: AssemblyTrademark("")]
// [assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("d88ae016-81f2-41f1-898e-2539a03eea43")]

// Version attributes are generated by MSBuild from <VizorVersion> in
// Directory.Build.props. Do not declare them here - duplicates break the build.
